apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-server
  namespace: mbaquer6
spec:
  replicas: 1
  selector:
    app: postgres-server
  template:
    metadata:
      name: postgres-server
      labels:
        app: postgres-server
        namespace: mbaquer6
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.8
        envFrom:
          - configMapRef:
              name: postgres-config 
        ports:
        - name: postgres-port
          containerPort: 5432
